install:
	install -d $(DESTDIR)/etc/qubes/repo-templates
	install -d $(DESTDIR)/etc/qubes/repo-templates/keys
	install -m 0644 qubes-templates.repo $(DESTDIR)/etc/qubes/repo-templates/qubes-templates.repo
	install -m 0644 RPM-GPG-KEY-qubes-4.1-primary $(DESTDIR)/etc/qubes/repo-templates/keys/RPM-GPG-KEY-qubes-4.1-primary
	install -m 0644 RPM-GPG-KEY-qubes-4.1-templates-community $(DESTDIR)/etc/qubes/repo-templates/keys/RPM-GPG-KEY-qubes-4.1-templates-community


